max_width = 80
tab_spaces = 2
use_field_init_shorthand = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
wrap_comments = true
ignore = ['api-prelude/src/errors/macros.rs']